spring.application.name=S5.02.bookstack

jwt.secret.key=U2VjcmV0S2V5MjEwN0F6aXomS2Vobm91dGExOTc1IUBEYWthcm9TZW5lZ2Fs

# Configuration MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bookstack?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MySQLCat1234!
spring.jpa.hibernate.ddl-auto=update
                                    # En production : preferez des migrations controlees (avec Flyway/Liquibase).

# Optimisations pour MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.oauth.client-id=test-client
springdoc.swagger-ui.oauth.realm=test-realm
springdoc.swagger-ui.oauth.scopes=openid,profile,email

